/**
 * Example words for kanji readings, generated by
 * scripts/generate-kanji-reading-examples.ts.
 */

/** [word, kana, meaning, soundsLike?] */
export type ReadingExample =
  | [string, string, string]
  | [string, string, string, string];

/** { [kanjiChar]: { [rawReading]: example } } */
export type ReadingExamples = Record<string, Record<string, ReadingExample>>;

let cache: ReadingExamples | null = null;
let pending: Promise<ReadingExamples> | null = null;

export const getReadingExamples = (): Promise<ReadingExamples> => {
  if (cache) return Promise.resolve(cache);
  pending ??= fetch('/data-kanji/reading-examples.json')
    .then(res => res.json() as Promise<ReadingExamples>)
    .then(data => {
      cache = data;
      return data;
    })
    .catch(() => {
      pending = null;
      return {};
    });
  return pending;
};

export const getCachedReadingExamples = (): ReadingExamples | null => cache;
