import { kana } from '@/features/Kana/data/kana';

// Clips are generated by scripts/generate-kana-audio.py into public/sounds/kana.
const CLIP_DIR = '/sounds/kana';

// Sounds the generator skips (the voice engine can't produce them); these fall
// back to the browser voice. Keep in sync with SKIP in the script.
const NO_CLIP = new Set(['ふゅ']);

export const toHiragana = (text: string): string =>
  Array.from(text, c => {
    const code = c.charCodeAt(0);
    return code >= 0x30a1 && code <= 0x30f6
      ? String.fromCharCode(code - 0x60)
      : c;
  }).join('');

const fileKey = (text: string): string =>
  Array.from(toHiragana(text), c => c.charCodeAt(0).toString(16)).join('-');

const clipKana = new Set(
  kana
    .flatMap(group => group.kana)
    .map(toHiragana)
    .filter(k => !NO_CLIP.has(k)),
);

/** Clip URL for a single kana (e.g. か, キャ), or null when there is none. */
export const getKanaClipSrc = (char: string): string | null =>
  clipKana.has(toHiragana(char)) ? `${CLIP_DIR}/${fileKey(char)}.mp3` : null;

/**
 * Clip URLs for a sequence of kana units (e.g. ['き', 'しゃ']), or null if any
 * unit has no clip, so the caller can fall back to speaking the whole string.
 */
export const getKanaClipSrcs = (units: string[]): string[] | null => {
  const srcs = units.map(getKanaClipSrc);
  return srcs.length > 0 && srcs.every(Boolean) ? (srcs as string[]) : null;
};
