/**
 * Pitch accents for vocabulary words, generated by
 * scripts/generate-vocab-pitch.ts from Kanjium (CC BY-SA 4.0).
 * Keyed by "word|kana"; values are downstep numbers, most common first.
 */
export type PitchAccents = Record<string, number[]>;

let cache: PitchAccents | null = null;
let pending: Promise<PitchAccents> | null = null;

export const getPitchAccents = (): Promise<PitchAccents> => {
  if (cache) return Promise.resolve(cache);
  pending ??= fetch('/data-vocab/pitch.json')
    .then(res => res.json() as Promise<PitchAccents>)
    .then(data => {
      cache = data;
      return data;
    })
    .catch(() => {
      pending = null;
      return {};
    });
  return pending;
};

export const getCachedPitchAccents = (): PitchAccents | null => cache;
