import type { RubyText } from '../types';
import { stripRuby } from './ruby';

// Clips are generated by scripts/generate-grammar-audio.py into
// public/sounds/grammar, named by a hash of the ruby text so any edit to a
// sentence gets a fresh clip.

/** 32-bit FNV-1a over code points, as 8 hex digits. Mirrored in the script. */
export function speechHash(text: string): string {
  let hash = 0x811c9dc5;
  for (const char of text) {
    hash ^= char.codePointAt(0)!;
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash.toString(16).padStart(8, '0');
}

export function getSentenceClipSrc(jp: RubyText): string {
  return `/sounds/grammar/${speechHash(jp)}.mp3`;
}

/**
 * Text for the browser voice when a clip is missing: '何[なん]／何[なに]' →
 * '何、何', '〜ません' → 'ません'.
 */
export function getSpeechText(jp: RubyText): string {
  return stripRuby(jp)
    .replace(/／/g, '、')
    .replace(/^[〜～]+|[〜～]+$/g, '');
}
