export interface ParsedReading {
  /** The entry as stored, e.g. "a(u) あ(う)" */
  raw: string;
  /** Romaji part, e.g. "a(u)" */
  romaji: string;
  /** Kana as displayed, with okurigana markers, e.g. "あ(う)" */
  kana: string;
  /** What to say out loud, e.g. "あう" */
  spoken: string;
  /** Kana the kanji itself covers, e.g. "あ" */
  stem: string;
  /** Trailing kana written after the kanji, e.g. "う" */
  okurigana: string;
  /** "-び": only used attached after other words (a suffix) */
  isSuffix: boolean;
  /** "お-": only used attached before other words (a prefix) */
  isPrefix: boolean;
}

// Data uses "a(u) あ(う)" or "く.る" for okurigana and "-" for affixes.
const OKURIGANA = /[(（.](.*?)[)）]?$/;

export const toHiragana = (text: string): string =>
  Array.from(text, c => {
    const code = c.charCodeAt(0);
    return code >= 0x30a1 && code <= 0x30f6
      ? String.fromCharCode(code - 0x60)
      : c;
  }).join('');

export const parseReading = (raw: string): ParsedReading => {
  const trimmed = raw.trim();
  const spaceIndex = trimmed.indexOf(' ');
  const romaji = spaceIndex === -1 ? '' : trimmed.slice(0, spaceIndex);
  const kana = spaceIndex === -1 ? trimmed : trimmed.slice(spaceIndex + 1);

  const isSuffix = kana.startsWith('-');
  const isPrefix = kana.endsWith('-');
  const core = kana.replace(/^-|-$/g, '');
  const match = core.match(OKURIGANA);
  const stem = match ? core.slice(0, match.index) : core;
  const okurigana = match ? match[1] : '';

  return {
    raw,
    romaji,
    kana,
    spoken: stem + okurigana,
    stem,
    okurigana,
    isSuffix,
    isPrefix,
  };
};

// Clips are generated by scripts/generate-reading-audio.py into
// public/sounds/readings, named by the hex code points of the hiragana form.
export const getReadingClipSrc = (reading: ParsedReading): string | null =>
  reading.spoken
    ? `/sounds/readings/${Array.from(toHiragana(reading.spoken), c =>
        c.charCodeAt(0).toString(16),
      ).join('-')}.mp3`
    : null;

/**
 * Audio for a kanji on its own: its first reading (the one shown as furigana
 * in quizzes), so the browser voice never has to guess which reading to use.
 */
export const getKanjiPromptAudio = (
  kanji: { onyomi: string[]; kunyomi: string[] } | undefined,
): { text: string; clipSrcs: string[] | null } | null => {
  const raw = kanji?.onyomi[0] || kanji?.kunyomi[0];
  if (!raw) return null;
  const reading = parseReading(raw);
  const clipSrc = getReadingClipSrc(reading);
  return { text: reading.spoken, clipSrcs: clipSrc ? [clipSrc] : null };
};
